### PR TITLE
fix: obtain supported platform versions from app store

### LINKED ISSUE #10: fetch versions, instead having a card coded  list
Currently, https://github.com/nextcloud/usercontent.apps.nextcloud.com/blob/master/sync.php#L28-L41 is maintained manually. Instead majors can be fetched from server git, from the appstore, …

### PR DESCRIPTION
**Pull request by edward-ly**
Fixes #10 and #17, plus a few minor improvements. As it stands, this would also remove 16.0.0 as a supported version since it is no longer supported in the app store.

### CODE REVIEW

File: sync.php [hunk 1]
```diff
@@ -1,57 +1,30 @@
...
- * This program is distributed in the hope that it will be useful,
- * but WITHOUT ANY WARRANTY; without even the implied warranty of
- * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
- * GNU Affero General Public License for more details.
- *
- * You should have received a copy of the GNU Affero General Public License
- * along with this program.  If not, see <http://www.gnu.org/licenses/>.
- *
+ * SPDX-FileCopyrightText: 2016-2025 Nextcloud GmbH and Nextcloud contributors
+ * SPDX-FileCopyrightText: 2016 Lukas Reschke <lukas@statuscode.ch>
```
Comment (nickvergessen) [inline sync.php:7]:
```suggestion
 * SPDX-FileCopyrightText: 2016-2025 Nextcloud GmbH and Nextcloud contributors
```

File: index.php [hunk 2]
```diff
@@ -1,22 +1,8 @@
...
- *
- * This program is distributed in the hope that it will be useful,
- * but WITHOUT ANY WARRANTY; without even the implied warranty of
- * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
- * GNU Affero General Public License for more details.
- *
- * You should have received a copy of the GNU Affero General Public License
- * along with this program.  If not, see <http://www.gnu.org/licenses/>.
- *
+ * SPDX-FileCopyrightText: 2016 Lukas Reschke <lukas@statuscode.ch>
```
Comment (nickvergessen) [inline index.php:4]:
```suggestion
 * SPDX-FileCopyrightText: 2016-2025 Nextcloud GmbH and Nextcloud contributors
```

File: README.md [hunk 3]
```diff
@@ -1,5 +1,21 @@
+<!--
+ - SPDX-FileCopyrightText: 2016-2025 Nextcloud GmbH and Nextcloud contributors
+ - SPDX-FileCopyrightText: 2016 Lukas Reschke <lukas@statuscode.ch>
```
Comment (nickvergessen) [inline README.md:3]:
```suggestion
```

File: .htaccess [hunk 4]
```diff
@@ -1,8 +1,11 @@
+# SPDX-FileCopyrightText: 2016 Lukas Reschke <lukas@statuscode.ch>
```
Comment (nickvergessen) [inline .htaccess:1]:
```suggestion
# SPDX-FileCopyrightText: 2016-2025 Nextcloud GmbH and Nextcloud contributors
```

**Review by nickvergessen — COMMENTED** [review]
This was employee work

**Comment by edward-ly** [comment]
> This was employee work

Thanks for the clarification, fixed.

File: sync.php [hunk 5]
```diff
@@ -1,57 +1,29 @@
 #!/usr/bin/env php
```
[the remark this answers is not in the document]
Comment (edward-ly) [reply sync.php:1]: It would allow the cron job to run `./sync.php` (taking advantage of the shebang) instead of `php sync.php`, but if you think that's not necessary, we can revert it.

[the remark this answers is not in the document]
Comment (edward-ly) [reply sync.php]: Executable bit reverted
